### ISSUE TITLE
Use SLF4J for logging

### ISSUE THREAD

**Issue by lptr** [gradle/gradle-fileevents#20]
This repo started as part of https://github.com/gradle/native-platform where we did not want to introduce a dependency just for Java-side logging, so we opted to use JUL. But now we don't have to be part of `native-platform`, so we can change this, and just use SLF4J like the rest of `gradle/gradle`.

This could simplify the interactions between the native logging and Gradle's own logging system by skipping the JUL-to-SLF4J bridge.

**Comment by Jocce-Nilsson** [comment]
➕ for this change. 
We expect it will help us remedy an issue where we have a huge logging overhead. 
We have seen INFO logs being printed on stderr without the `--info` flag set in Gradle.
